language: python
python:
  - "3.6"
before_install:
  - pip install git+git://github.com/Azure/azure-multiapi-storage-python.git
install:
  - pip install azure
script:
  - pytest
  - python script.py args ACCOUNT_NAME, ACCOUNT_KEY