language: python
python:
  - "3.6"
before_install:
  - pip install git+git://github.com/Azure/azure-multiapi-storage-python.git
install:
  - pip install azure
env:
  - "ACCOUNT_KEY"
  - "ACCOUNT_NAME"
script:
  - pytest
  - python script.py