language: python
python:
  - "3.6"
install:
  - pip install --upgrade pip
  - pip install git+git://github.com/Azure/azure-sdk-for-python
  - pip install azure-mgmt-storage
script:
  - pytest
  - python script.py