language: ruby
before_install:
  - gem update --system
  - gem --version
  - gem sources --remove https://rubygems.org/
  - gem sources -a http://rubygems.org/
install: gem install azure-blob-storage
script: uploadScript.rb


