language: python
python:
  - "3.6"
install:
  - pip git:https//github.com/azure/azure-storage-python
  - pip install azure
  - pip install azure-storage-blob
  - pip install azure-storage-file
  - pip install azure-storage-queue
script:
  - pytest
  - python script.py